version: "3.9"

services:
  app:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file:
      - ./db_deployments/db_config.env
    ports:
      - ${MAIN_SERVER_DEV_PORT:-8001}:8080
    networks:
      - network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - ./db_deployments/db_config.env
    ports:
      - ${DB_PORT:-27017}:27017
    networks:
      - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${DB_NAME:-solnyshko}
    volumes:
      - ./db_deployments/db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro

  adminer:
    image: mongo-express
    container_name: mongo-adminer
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${DB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${DB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - '8081:8081'
    networks:
      - network
    depends_on:
      - mongo

networks:
  network:
    driver: bridge