version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - db_config.env
    ports:
      - ${MONGODB_PORT:-27017}:27017
    networks:
      - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-root}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-solnyshko}
    volumes:
      - ./assets/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh

  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-17860}:8080
    networks:
      - network
    depends_on:
      - mongo

networks:
  network:
    driver: bridge