version: "3.9"

services:
  #  app:
  #    container_name: server
  #    build:
  #      context: ./server
  #      dockerfile: ./Dockerfile
  #    env_file:
  #      - ./db_deployments/db_config.env
  #    ports:
  #      - ${MAIN_SERVER_DEV_PORT:-8080}:8080
  #    networks:
  #      - network
  #    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - db_deployments/db_config.env
    ports:
      - ${DB_PORT:-27017}:27017
    networks:
      - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${DB_NAME:-solnyshko}
    volumes:
      - ./db_deployments/db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro

  keycloak:
    networks:
      - network
    ports:
      - "8086:8080"
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

networks:
  network:
    driver: bridge